### ISSUE TITLE
IOS Not Play path or Http

### ISSUE THREAD

**Issue by TimBarton** [amccorma/xamarin-amccorma#1]
Hi,

when you set the path to be http or a /...., you get a black screen with no video playing.  Your sample.mp4 plays fine.

Thanks

**Comment by TimBarton** [comment]
It took me a a little bit to figure it out but I found the issue.  I had to change the Load procedure in MyPlayerView.cs to accept NSString instead of string.  I then cast all strings to NSString that used the procedure.  No all is playing for local references.

protected internal void Load(NSString file)
        {
            // file must be set to Content
            // url starts with http

```
        if (String.IsNullOrEmpty (file) == false) {
            if (file.ToString().ToLower().StartsWith ("http") == false) {
                this._MoviePlayer.Load (NSUrl.FromFilename (file), false);
            } else {
                this._MoviePlayer.Load (NSUrl.FromString (file), true);
            }
        }
    }
```

**Comment by amccorma** [comment]
thanks for the fix. updated the project
