### ISSUE TITLE
Masked crash in SetBinding

### ISSUE THREAD

**Issue by elyfran** [amccorma/xamarin-amccorma#2]
When i set "SetBinding" in "MyEntry" item the app crash.

 var cmpPhone = new MyEntry();
  ...
cmpPhone.SetBinding(Entry.TextProperty, new Binding("Phone"));

**Comment by amccorma** [comment]
I try to fix the bug this weekend

**Comment by elyfran** [comment]
HI,
you could make an effort to verficiar it as quickly as possible ? because I need to pdoer validate a screen.

Thx

**Comment by amccorma** [comment]
What project was the exception in?

**Comment by elyfran** [comment]
System.NullReferenceException: Object references not set on an instance of an Object. as Masked.Controls.MyEnry,<.ctor> b__61_0 (System.Object sender, Xamarin.Forms.TextChangedEventArgs e)
...

![erro_entry](https://cloud.githubusercontent.com/assets/2677011/15446209/54ed1d4c-1eee-11e6-8eeb-3db2e809d95c.png)

**Comment by amccorma** [comment]
I uploaded an mvvm sample.  I could not reproduce any errors.  If you having problems upload a sample to github for me to look at.

**Comment by elyfran** [comment]
Your example is not a problem. to reproduce the error just add SetBinding the component and type something

**Comment by elyfran** [comment]
If you type something with setbiding the application crashes

**Comment by amccorma** [comment]
I did that.
https://github.com/amccorma/xamarin-amccorma/blob/master/MaskedEdit/Page1.cs

And typed something. Did not get an exception. Android or iOS?

**Comment by elyfran** [comment]
the same error occurs . I tested it in your github project with the code sent .

![exemplo01](https://cloud.githubusercontent.com/assets/2677011/15459786/5c6453c8-207f-11e6-9fad-796ee731977e.png)
![exemplo02](https://cloud.githubusercontent.com/assets/2677011/15459787/5c6880f6-207f-11e6-9353-7d753efec0ff.png)

**Comment by amccorma** [comment]
I found the issue.  fixed. updated solution.  download the zip file.

**Comment by elyfran** [comment]
nice job... thx =D
