### ISSUE TITLE
[iOS][MarqueeLabel] Visual Studio iOS Simulator error

### ISSUE THREAD

**Issue by andreabellitto** [amccorma/xamarin-amccorma#4]
I'm using MarqueeLabelBinding.dll reference inside my project, but i have an error when try to access this row inside MarqueeLabelRenderer.cs

`label = new MarqueeLabel (this.Bounds);`

I receive this exception:

`System.Exception: Could not create an native instance of the type 'MarqueeLabel': the native class hasn't been loaded.`

**Comment by amccorma** [comment]
Be fixed by Monday afternoon. Limited access over the weekend to the source to replace the files uploaded. I use this control in my iOS projects and must have missed file to upload.

**Comment by amccorma** [comment]
posting new version in a few minutes

**Comment by amccorma** [comment]
updated.  issue was binding with new Xamarin nuget package.  fixed and added test samples for iOS and Xamarin Forms.

**Comment by amccorma** [comment]
Thanks for the code change
